branches:
  only:
    - main
    - dev

environment:
  CONAN_RUN_TESTS: True
  CONAN_V2_MODE: 1
  CONAN_REVISIONS_ENABLED: 1
  CONAN_SCM_TO_CONANDATA: 1

cache:
  - "$HOME/.cache/ccache" 
  - "$HOME/.cache/pip"
  - "$HOME/.conan2/p"

image:
  - Visual Studio 2019
  - Ubuntu2204
  - macos-monterey

install:
  - pip install cmake conan ninja --upgrade
  - conan profile detect -f

build_script:
  - cd imagelib
  - sh: export PROJECT_NAME=$(cat name.txt)
  - sh: export PROJECT_VERSION=$(cat version.txt)
  - ps: $PROJECT_NAME = Get-Content name.txt -Raw
  - ps: $PROJECT_VERSION = Get-Content version.txt -Raw
  - conan create . -b missing
  - conan test integration $PROJECT_NAME/$PROJECT_VERSION
