branches:
  only:
    - main
    - release
    - dev

environment:
  matrix:
    - WORKING_DIRECTORY: ./imagelib
      CONAN_RUN_TESTS: True
      CONAN_V2_MODE: 1
      CONAN_REVISIONS_ENABLED: 1
      CONAN_SCM_TO_CONANDATA: 1

cache:
  # pip cache
  - C:\Users\appveyor\AppData\Local\pip\Cache -> .appveyor.yml
  - /home/appveyor/.cache/pip -> .appveyor.yml
  # conan cache
  - C:\Users\appveyor\.conan2\p
  - /home/appveyor/.conan2/p
  # CCache cache
  - /home/appveyor/.cache/ccache

image:
  - Visual Studio 2019
  - Ubuntu2204
  - macos-monterey

install:
  - pip install cmake ninja conan --upgrade --user
  - cmake --version
  - ninja --version
  - conan --version
  - conan profile detect -f

build_script:
  - cmd: |
      cd %WORKING_DIRECTORY%
      set /p PROJECT_NAME=<name.txt
      set /p PROJECT_VERSION=<version.txt
      conan create . -b missing
      conan test integration %PROJECT_NAME%/%PROJECT_VERSION%
  - sh: |
      cd $WORKING_DIRECTORY
      export PROJECT_NAME=$(cat name.txt)
      export PROJECT_VERSION=$(cat version.txt)
      conan create . -b missing
      conan test integration $PROJECT_NAME/$PROJECT_VERSION
