language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      arch: amd64
      dist: jammy
      compiler: gcc

    - os: linux
      arch: ppc64le
      dist: jammy
      compiler: gcc

    - os: linux
      arch: s390x
      dist: jammy
      compiler: gcc

    - os: linux
      arch: arm64  
      dist: jammy
      compiler: gcc

    - os: osx
      osx_image: xcode14.2
      compiler: clang

addons:
  apt:
    packages:
      - ccache
      - python3
      - python3-pip

  homebrew:
    packages:
      - ccache
      - python3

env:
  global:
    - CONAN_V2_MODE=1
    - CONAN_REVISIONS_ENABLED=1
    - CONAN_SCM_TO_CONANDATA=1

cache:
  - pip
  - ccache
  - directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.conan2/p 

install:
  - pip3 install cmake ninja conan --upgrade
  - conan profile detect -f

before_script:
  - cd imagelib

script:
  - conan install . -s build_type=Release -b missing
  - cmake --workflow --fresh --preset ci
