language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      osx_image: xcode10.2
      compiler: clang

addons:
  apt:
    packages:
      - ccache
      - python3-pip
  homebrew:
    packages:
      - ccache
      - python3

env:
  global:
    - CONAN_V2_MODE=1
    - CONAN_REVISIONS_ENABLED=1
    - CONAN_SCM_TO_CONANDATA=1

cache:
  - pip
  - ccache
  - directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - pip install cmake ninja conan --upgrade --user
  - cmake --version
  - ninja --version
  - conan --version
  - conan user

install:
  - conan profile detect

before_script:
  - cd imagelib

script:
  - conan install . -b missing
  - cmake --workflow --fresh --preset ci
