language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - ccache
      - python3
      - python3-pip
  homebrew:
    packages:
      - ccache
      - python3

env:
  global:
    - CONAN_V2_MODE=1
    - CONAN_REVISIONS_ENABLED=1
    - CONAN_SCM_TO_CONANDATA=1

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/.cache/pip
    - $HOME/.ccache
    - $HOME/.conan2

install:
  - pip3 install cmake ninja conan --upgrade --user
  - conan profile detect

before_script:
  - cd imagelib

script:
  - conan install . -b missing
  - cmake --workflow --fresh --preset ci
