language: python
python: "3.7"
os:
  - linux
  - windows
  - osx
      
install:
  - pip install conan
  - conan user

before_script:
  - cd imagelib

script:
  - conan install . -b missing
  - cmake --workflow --fresh --preset ci
