---
language: minimal
dist: bionic

matrix:
  include:
    - name: OSX (xcode11.3 clang-11.0.0)
      os: osx
      osx_image: xcode11.3
    - name: Linux amd64 (gcc-9)
      os: linux
      addons:
        apt:
          packages: g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9
    - name: Linux arm64 (gcc-9)
      os: linux
      arch: arm64
      addons:
        apt:
          packages: g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9
    - name: Linux s390x (gcc-9)
      os: linux
      arch: s390x
      addons:
        apt:
          packages: g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9
    - name: Linux ppc64le (gcc-9)
      os: linux
      arch: ppc64le
      addons:
        apt:
          packages: g++-9
      env:
        - CXX=g++-9
        - CC=gcc-9
    - name: Linux amd64 (clang)
      os: linux
      env:
        - CXX=clang++
        - CC=clang
    - name: Linux arm64 (clang)
      os: linux
      arch: arm64
      env:
        - CXX=clang++
        - CC=clang
    - name: Linux s390x (clang)
      os: linux
      arch: s390x
      env:
        - CXX=clang++
        - CC=clang
    - name: Linux ppc64le (clang)
      os: linux
      arch: ppc64le
      env:
        - CXX=clang++
        - CC=clang

addons:
  apt:
    packages:
      - ccache
      - python3
      - python3-pip
  homebrew:
    packages:
      - ccache
      - python3

env:
  global:
    - WORKING_DIRECTORY=./imagelib
    - CONAN_RUN_TESTS=1
    - CONAN_V2_MODE=1
    - CONAN_REVISIONS_ENABLED=1
    - CONAN_SCM_TO_CONANDATA=1

cache:
  - pip
  - ccache
  - directories:
    - $HOME/.conan2/p 

install:
  - pip3 install cmake ninja conan --upgrade
  - conan profile detect -f

script:
  - cd $WORKING_DIRECTORY
  - conan create . -b missing
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export PROJECT_NAME=$(type %WORKING_DIRECTORY%/name.txt)
      export PROJECT_VERSION=$(type %WORKING_DIRECTORY%/version.txt)
      conan test integration %PROJECT_NAME%/%PROJECT_VERSION%
    else
      export PROJECT_NAME=$(cat $WORKING_DIRECTORY/name.txt)
      export PROJECT_VERSION=$(cat $WORKING_DIRECTORY/version.txt)
      conan test integration $PROJECT_NAME/$PROJECT_VERSION
    fi

