---
format:
  line_width: 80
lint:
  disabled_codes: []
  function_pattern: '[a-z][a-z0-9_]+'
  macro_pattern: '[A-Z_][A-Z0-9_]+'
  global_var_pattern: '[A-Za-z][0-9a-zA-Z_]+'
  internal_var_pattern: '[A-Za-z_][0-9a-zA-Z_]+'
  local_var_pattern: '[A-Za-z][A-Za-z0-9_]+'
  private_var_pattern: _[A-Z][A-Z0-9_]+
  public_var_pattern: '[A-Z][0-9A-Z_]+'
  argument_var_pattern: '[a-z][A-Za-z0-9_]+'
  keyword_pattern: '[A-Z][A-Z0-9_]+'
  max_statement_spacing: 2
  max_returns: 6
  max_branches: 50
  max_arguments: 5
  max_localvars: 15
  max_statements: 250
