language: cpp

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: windows
      compiler: gcc
    - os: windows
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y cmake ninja-build; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install cmake ninja; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install cmake ninja; fi
  - pip install conan

install:
  - conan install .

script:
  - cmake --workflow --fresh --preset ci-${CC}
