if(EXISTS "C:/workspace/PNGProcessor/tests/unit_tests/unit_tests[1]_tests.cmake")
  include("C:/workspace/PNGProcessor/tests/unit_tests/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
