include_guard()

if (ENABLE_CCACHE)
    find_program(CCACHE_FOUND ccache)
    if(CCACHE_FOUND)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
        set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
        message(STATUS "CCache enabled")
    else (CCACHE_FOUND)
        message(FATAL_ERROR "Could not found ccache!")
        message(STATUS "CCache disabled")
        set(ENABLE_CCACHE OFF)
    endif(CCACHE_FOUND)
else (ENABLE_CCACHE)
    message(STATUS "CCache disabled")
endif (ENABLE_CCACHE)
