include_guard()

if (ENABLE_ASAN)
    if (NOT MSVC)
        add_compile_options(-fsanitize=address)
        add_link_options(-fsanitize=address)
        message(STATUS "Address sanitizer enabled")
        if (UNIX)
            add_compile_options(-fsanitize=leak)
            add_link_options(-fsanitize=leak)
            message(STATUS "Leak sanitizer enabled")
        endif (UNIX)
        if (APPLE)
            add_compile_options(-fsanitize=memory)
            add_link_options(-fsanitize=memory)
            message(STATUS "Memory sanitizer enabled")
        endif (APPLE)
    else (NOT MSVC)
        message(STATUS "Address sanitizer is unsupported!")
        message(STATUS "Address sanitizer disabled")
    endif(NOT MSVC)
else (ENABLE_ASAN)
    message(STATUS "Address sanitizer disabled")
endif(ENABLE_ASAN)


if (ENABLE_TSAN)
    if (NOT MSVC)
        add_compile_options(-fsanitize=thread)
        add_link_options(-fsanitize=thread)
        message(STATUS "Thread sanitizer enabled")
    else (NOT MSVC)
        message(STATUS "Thread sanitizer is unsupported!")
        message(STATUS "Thread sanitizer disabled")
    endif(NOT MSVC)
else (ENABLE_TSAN)
    message(STATUS "Thread sanitizer disabled")
endif(ENABLE_TSAN)

if (ENABLE_UBSAN)
  if (NOT MSVC)
      add_compile_options(-fsanitize=undefined)
      add_link_options(-fsanitize=undefined)
      message(STATUS "Undefined sanitizer enabled")
  else (NOT MSVC)
      message(STATUS "Undefined sanitizer is unsupported!")
      message(STATUS "Undefined sanitizer disabled")
  endif(NOT MSVC)
else (ENABLE_UBSAN)
    message(STATUS "Undefined sanitizer disabled")
endif(ENABLE_UBSAN)
