#pragma once

#define PNGPROCESSOR_VERSION_MAJOR 1
#define PNGPROCESSOR_VERSION_MINOR 0
#define PNGPROCESSOR_VERSION_PATCH 0

#define PNGPROCESSOR_VERSION \
  (PNGPROCESSOR_VERSION_MAJOR * 1000 \
  + PNGPROCESSOR_VERSION_MINOR * 100 \
  + PNGPROCESSOR_VERSION_PATCH)

#define PNGPROCESSOR_VERSION_STRING "1.0.0"
