if (NOT MSVC)
if (ENABLE_ASAN)
  add_compile_options("-fsanitize=address")
  add_link_options("-fsanitize=address")
endif()

if (ENABLE_LSAN)
  message(STATUS "Leak sanitizer is enabled")
  add_compile_options("-fsanitize=leak")
  add_link_options("-fsanitize=leak")
endif()

if (ENABLE_MSAN)
  message(STATUS "Memory sanitizer is enabled")
  add_compile_options("-fsanitize=memory")
  add_link_options("-fsanitize=memory")
endif()

if (ENABLE_TSAN)
  message(STATUS "Thread sanitizer is enabled")
  add_compile_options("-fsanitize=thread")
  add_link_options("-fsanitize=thread")
endif()

if (ENABLE_UBSAN)
  message(STATUS "Undefined sanitizer is enabled")
  add_compile_options("-fsanitize=undefined")
  add_link_options("-fsanitize=undefined")
endif()
else()
  message(WARNING "Sanity checks are unsupported for Visual Studio!")
endif()