include_guard(GLOBAL)

option(WITH_CCACHE "Enable ccache for speeding up compilation process" ON)
if (WITH_CCACHE)
  find_program(CCACHE_PROGRAM ccache)
  if (NOT CCACHE_PROGRAM)
    message(WARNING "Could not find ccache")
    message(STATUS "Feature: ccache skipped")
    return()
  endif (NOT CCACHE_PROGRAM)
   set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_PROGRAM})
   set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ${CCACHE_PROGRAM})
   message(STATUS "Feature: ccache enabled")
else (WITH_CCACHE)
  message(STATUS "Feature: ccache disabled")
endif (WITH_CCACHE)
