include_guard()

message(STATUS "***** toolchain-msvc.cmake")

if (NOT DEFINED CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER cl)
endif (NOT DEFINED CMAKE_C_COMPILER)

if (NOT DEFINED CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER cl)
endif (NOT DEFINED CMAKE_CXX_COMPILER)

include(${CMAKE_CURRENT_LIST_DIR}/overrides-msvc.cmake)

set(_LANGUAGES C CXX)
set(_BUILD_TYPES "" _DEBUG _RELEASE _MINSIZEREL _RELWITHDEBINFO)
set(_LINK_TYPES EXE STATIC SHARED MODULE)

message(STATUS "CMAKE_SYSTEM_NAME = ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR = ${CMAKE_SYSTEM_PROCESSOR}")

foreach(_LANGUAGE ${_LANGUAGES})
    message(STATUS "CMAKE_${_LANGUAGE}_COMPILER = ${CMAKE_${_LANGUAGE}_COMPILER}")
endforeach(_LANGUAGE ${_LANGUAGES})

message(STATUS "CMAKE_LINKER = ${CMAKE_LINKER}")

foreach(_LANGUAGE ${_LANGUAGES})
    message(STATUS "CMAKE_${_LANGUAGE}_LINKER = ${CMAKE_${_LANGUAGE}_LINKER}")
endforeach(_LANGUAGE ${_LANGUAGES})

foreach(_LANGUAGE ${_LANGUAGES})
    foreach(_BUILD_TYPE ${_BUILD_TYPES})
        message(STATUS "CMAKE_${_LANGUAGE}_FLAGS${_BUILD_TYPE} = ${CMAKE_${_LANGUAGE}_FLAGS${_BUILD_TYPE}}")
    endforeach(_BUILD_TYPE ${_BUILD_TYPES})
endforeach(_LANGUAGE ${_LANGUAGES})

foreach(_LINK_TYPE ${_LINK_TYPES})
    foreach(_BUILD_TYPE ${_BUILD_TYPES})
        message(STATUS "CMAKE_${_LINK_TYPE}_LINKER_FLAGS${_BUILD_TYPE} = ${CMAKE_${_LINK_TYPE}_LINKER_FLAGS${_BUILD_TYPE}}")
    endforeach(_BUILD_TYPE ${_BUILD_TYPES})
endforeach(_LINK_TYPE ${_LINK_TYPES})

message(STATUS "***** toolchain-msvc.cmake")
