name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu, macos, windows ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install conan
      - if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: mkdir -p build
      - id: archive_data
        working-directory: ${{ github.workspace }}/build
        run: |
          conan install .. -s build_type=Release -pr:b default --build missing
          conan build ..
          conan package ..
          echo "::set-output name=archive_name::$(cat archive_name.txt)"
          echo "::set-output name=archive_path::$(cat archive_path.txt)"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.archive_data.outputs.archive_name }}
          path: ${{ steps.archive_data.outputs.archive_path }}
