name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: project-init-cpp-linux-x86_64.zip
            asset_path: package/archive/project-init-cpp-linux-x86_64.tar.gz
          - os: macos-latest
            asset_name: project-init-cpp-darwin-x86_64.zip
            asset_path: package/archive/project-init-cpp-darwin-x86_64.tar.gz
          - os: windows-latest
            asset_name: project-init-cpp-windows-x86_64.zip
            asset_path: package/archive/project-init-cpp-windows-x86_64.zip

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install conan
      - if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install . -if install -s build_type=${{ env.BUILD_TYPE }} -pr:b default --build missing
      - run: conan build . -bf build -if install
      - run: conan package . -pf package -bf build -if install
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_path }}
