name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.vm }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
       include:
         - name: linux
           vm: ubuntu-latest
           os: Linux
           arch: x86_64
           compiler: gcc
           compiler_version: 9
           compiler_libcxx: libstdc++11

         - name: macos
           vm: macos-latest
           os: Macos
           arch: x86_64
           compiler: apple-clang
           compiler_version: 13.0
           compiler_libcxx: libc++

         - name: windows
           vm: windows-latest
           os: Windows
           arch: x86_64
           compiler: "Visual Studio"
           compiler_version: 17

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Get current branch
        id: get_current_branch
        run: |
          echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      # For speeding up the build, let's create a cache for conan packages.
      # A new branch will create a copy of the master cache,
      # but the master cache isn't updated until a merge to the master branch.
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.get_current_branch.outputs.name }}
          restore-keys: |
            conan-package-cache-master

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name: Install linux packages required by SDL
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -y install libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev libxcb-util-dev libegl-dev

      - name: Install/Upgrade Conan
        shell: bash
        run: |
          pip3 install --upgrade conan
          conan --version
          conan user
          conan profile new --force default
          conan profile update settings.os="${{ matrix.os }}" default
          conan profile update settings.os_build="${{ matrix.os }}" default
          conan profile update settings.arch="${{ matrix.arch }}" default
          conan profile update settings.arch_build="${{ matrix.arch }}" default
          conan profile update settings.compiler="${{ matrix.compiler }}" default
          conan profile update settings.compiler.version="${{ matrix.compiler_version }}" default
          conan profile update settings.compiler.libcxx="${{ matrix.compiler_libcxx }}" default
          conan profile show default

      - name: Remove uncompatible conan setting for Visual Studio
        shell: bash
        if: matrix.compiler == 'Visual Studio'
        run: conan profile remove settings.compiler.libcxx default

      - name: Create build environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Install dependencies
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: conan install .. -s build_type=${{ env.BUILD_TYPE }} -o with_presets=True -o with_tests=True -o with_archive=True -pr:b default --build missing

      - name: Run build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: conan build ..

      - name: Package
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: conan package ..

      - name: Get project details
        id: get_project_details
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          echo "::set-output name=name::$(cat NAME)"
          echo "::set-output name=version::$(cat VERSION)"

      - name: Remove package from local cache
        run: conan remove ${{ steps.get_project_details.outputs.name }}/${{ steps.get_project_details.outputs.version }} -f

      - name: Export package
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: conan export-pkg .. user/channel -if tmp/install -bf tmp/build

      - name: Run integration test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: conan test ../integration ${{ steps.this_project.outputs.name }}/${{ steps.this_project.outputs.version }}@user/channel -s build_type=${{ env.BUILD_TYPE }} --build missing

      - name: Get package details
        id: get_package_details
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          echo "::set-output name=name::$(basename "$(find "." -maxdepth 1 -name "${{ steps.get_project_details.outputs.name }}*.zip" -or -name "${{ steps.get_project_details.outputs.name }}*.tar.gz")")"
          echo "::set-output name=path::$(find "." -maxdepth 1 -name "${{ steps.get_project_details.outputs.name }}*.zip" -or -name "${{ steps.get_project_details.outputs.name }}*.tar.gz")"

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get_package_details.outputs.name }}
          path: ${{ steps.get_package_details.outputs.path }}

  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install documentation tools
        shell: bash
        run: sudo apt install doxygen graphviz texlive-latex-extra

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake -DBUILD_DOC=TRUE ..

      - name: Build API documentation
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target doxydoc pdfdoc

      - name: Get project details
        id: get_project_details
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          echo "::set-output name=name::$(cat NAME)"

      - name: Get user manual details
        id: get_user_manual_details
        shell: bash
        working-directory: ${{runner.workspace}}/build/doc
        run: |
          echo "::set-output name=name::$(basename "$(find "." -maxdepth 1 -name "${{ steps.get_project_details.outputs.name }}*.pdf")")"
          echo "::set-output name=path::$(find "." -maxdepth 1 -name "${{ steps.get_project_details.outputs.name }}*.pdf")"

      - name: Upload user manual
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get_user_manual_details.outputs.name }}
          path: ${{ steps.get_user_manual_details.outputs.path }}
