name: build
on: 
  pull_request:
  push:
    branches:
      - master

env:
  CONAN_V2_MODE: true
  CONAN_REVISIONS_ENABLED: true
  CONAN_SCM_TO_CONANDATA: true
  CONAN_SYSREQUIRES_MODE: enabled

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install conan
      - id: branch_data
        shell: bash
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.branch_data.outputs.name }}
          restore-keys: |
            conan-package-cache-master
      - run: cmake -E make_directory ${{ github.workspace }}/build
      - working-directory: ${{ github.workspace }}/build
        run: conan install .. -pr:b default --build missing
      - working-directory: ${{ github.workspace }}/build
        run: conan build ..
      - id: archive_data
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: echo "::set-output name=name::$(cat archive_name.txt)"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.archive_data.outputs.name }}
          path: ./build/${{ steps.archive_data.outputs.name }}
