name: build-linux-gcc
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Acquire branch name
        id: current_branch
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-cache-${{ steps.current_branch.outputs.name }}
          restore-keys: conan-cache-main
      - name: Install prerequisites
        run: sudo apt install -y lcov doxygen graphviz texlive-latex-extra
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Conan
        run: pip3 install --upgrade conan
      - name: Update Conan profile
        run: conan profile detect -f
      - name: Pull Dependencies
        run: conan install . -of build -s build_type ${{ env.BUILD_TYPE }} -pr:b=default -b=missing
      - name: Configure
        run: cmake --preset ci-gcc ${{ github.workspace }}
      - name: Build
        run: cmake --build --preset ci-gcc
      - name: Test
        run: ctest --preset ci-gcc
      - name: Coverage
        run: cmake --build --target cov
      - name: Generate documentation
        run: cmake --build --target doc
      - name: Package
        run: cpack
