name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
       include:
         - os: ubuntu
         - os: macos
         - os: windows

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install conan
      # gtest requires c++11 conan profile explicitly
      - if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: cmake -E make_directory ${{ github.workspace }}/build
      - working-directory: ${{ github.workspace }}/build
        run: conan install .. -s build_type=${{ env.BUILD_TYPE }} -pr:b default --build missing
      - working-directory: ${{ github.workspace }}/build
        run: conan build ..
      - working-directory: ${{ github.workspace }}/build
        run: conan package ..
      - working-directory: ${{ github.workspace }}/build
        id: artifact_data
        run: |
          echo "::set-output name=name::$(cat artifact_name.txt)"
          echo "::set-output name=path::$(cat artifact_path.txt)"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifact_data.outputs.name }}
          path: ${{ steps.artifact_data.outputs.path }}
