name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install conan
      - if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install . -if install -s build_type=${{ env.BUILD_TYPE }} -pr:b default --build missing
      - run: conan build . -bf build -if install
      - run: conan package . -pf package -bf build -if install
      - id: archive_info
        run: |
          echo "::set-output name=archive_path::$(cat ./build/archive_path.txt)"
          echo "::set-output name=archive_name::$(cat ./build/archive_name.txt)"
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.archive_info.outputs.archive_path }}
          name: ${{ steps.archive_info.outputs.archive_name }}
