name: build
on: 
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - id: branch_data
        shell: bash
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.branch_data.outputs.name }}
          restore-keys: |
            conan-package-cache-master
      - run: pip3 install --upgrade --user conan
      - if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: cmake -E make_directory ${{ github.workspace }}/build
      - run: |
          conan config set general.request_timeout=120
          conan install . -if install -pr:b default --build missing
      - run: conan build . -if install -bf build
      - run: conan package . -if install -bf build -pf package
      - id: archive_data
        shell: bash
        run: echo "::set-output name=name::$(cat ./build/archive_name.txt)"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.archive_data.outputs.name }}
          path: ./build/${{ steps.archive_data.outputs.name }}
