name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONAN_V2_MODE: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu
          - os: macos
          - os: windows

    steps:
      - uses: actions/checkout@v2
      - id: this_branch
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.this_branch.outputs.name }}
          restore-keys: |
            conan-package-cache-master
      - run: pip3 install conan
      - run: cmake -E make_directory ${{ github.workspace }}/build
      - run: conan install .. --build missing
        working-directory: ${{ github.workspace }}/build
      - run: conan build ..
        working-directory: ${{ github.workspace }}/build
      - run: conan package ..
        working-directory: ${{ github.workspace }}/build
      - id: this_artifact
        run: |
          echo "::set-output name=name::$(cat artifact_name.txt)"
          echo "::set-output name=path::$(cat artifact_path.txt)"
        working-directory: ${{ github.workspace }}/build
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.this_artifact.outputs.name }}
          path: ${{ steps.this_artifact.outputs.path }}
