name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CONAN_LOG_RUN_TO_FILE: true
  CONAN_LOG_RUN_TO_OUTPUT: false
  CONAN_SYSREQUIRES_SUDO: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      working-directory: ./imageutils

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang, msvc]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: msvc
          - os: macos-latest
            compiler: msvc

    steps:
      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@v4

      - id: current_branch
        run: echo "name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.current_branch.outputs.name }}
          restore-keys: |
            conan-package-cache-main

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup environment
        run: |
          pip3 install --upgrade conan
          conan --version
          conan profile detect
          conan profile list
          conan profile show

      - name: Download dependencies
        run: conan install . -b missing
        working-directory: ${{ env.working-directory }}

      - name: Build
        run: cmake --workflow --fresh --preset ci-${{ matrix.compiler }}
        working-directory: ${{ env.working-directory }}
