name: release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build-release:
    runs-on: ${{ matrix.vm }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
       include:
         - name: linux
           vm: ubuntu-latest
           os: Linux
           compiler: "gcc"
 
         - name: macos
           vm: macos-latest
           os: Macos
           compiler: "clang"

         - name: windows
           vm: windows-latest
           os: Windows
           compiler: "msvc"

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Retrieve current branch name
        id: current_branch
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.current_branch.outputs.name }}
          restore-keys: |
            conan-package-cache-master

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name: Install linux packages required by coverage
        if: startsWith(matrix.name, 'linux') || startsWith(matrix.name, 'macos')
        run: |
          sudo apt-get -y install lcov

      - name: Install documentation tools
        if: startsWith(matrix.name, 'linux') || startsWith(matrix.name, 'macos')
        run: |
          sudo apt install -y doxygen graphviz texlive-latex-extra
