name: release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 30

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu, macos, windows ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip3 install conan
      - if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - run: conan install . -if install -s build_type=${{ env.BUILD_TYPE }} -pr:b default --build missing
      - run: conan build . -bf build -if install
      - run: conan package . -pf package -bf build -if install
      - id: asset_info
        run: |
          echo "::set-output name=asset_name::$(cat ./build/asset_name.txt)"
          echo "::set-output name=asset_path::$(cat ./build/asset_path.txt)"
      - run: echo '${{ steps.archive_info.outputs.asset_name }}' > asset_name_${{ matrix.os }}.txt
      - run: echo '${{ steps.archive_info.outputs.asset_path }}' > asset_path_${{ matrix.os }}.txt
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.archive_info.outputs.asset_name }}
          path: ${{ steps.archive_info.outputs.asset_path }}
      - uses: actions/upload-artifact@v3
        with:
          name: asset_name_${{ matrix.os }}
          path: asset_name_${{ matrix.os }}.txt
      - uses: actions/upload-artifact@v3
        with:
          name: asset_path_${{ matrix.os }}
          path: asset_path_${{ matrix.os }}.txt

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-artifact
    steps:
      - uses: actions/checkout@v2
      - uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ env.BUILD_TYPE }}
          draft: false
          prerelease: false
      - run: echo '${{ steps.release.outputs.upload_url }}' > upload_url.txt
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: upload_url.txt

  upload-release:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        os: [ ubuntu, macos, windows ]

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: archive_name_${{ matrix.os }}
    - uses: actions/download-artifact@v2
      with:
        name: release
    - id: release
      run: echo "::set-output name=upload_url::$(cat upload_url.txt)"
    - id: asset_info
      run: |
        echo "::set-output name=asset_name::$(cat asset_name_${{ matrix_os }})"
        echo "::set-output name=asset_path::$(cat asset_path_${{ matrix_os }})"
        echo "::set-output name=asset_content_type::$(if [ runner.os == "Windows" ]; then echo "application/zip"; else echo "application/gzip"; fi)"
    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_name: ${{ steps.asset_info.outputs.asset_name }}
        asset_path: ${{ steps.asset_info.outputs.asset_path }}
        asset_content_type: ${{ steps.asset_info.outputs.asset_content_type }}
