name: release

on:
  push:
    tags:
      - 'v*'

env:
  BUILD_TYPE: Release

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
       include:
         - name: linux
           os: ubuntu-latest
           compiler: gcc
           compiler_version: 9
           compiler_libcxx: libstdc++11

         - name: mac
           os: macos-latest
           compiler: apple-clang
           compiler_version: 13.0
           compiler_libcxx: libc++

         - name: windows
           os: windows-latest
           compiler: Visual Studio
           compiler_version: 16
           compiler_libcxx: cppstd

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Retrieve current branch name
        id: this_branch
        run: |
          echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"

      # For speeding up the build, let's create a cache for conan packages.
      # A new branch will create a copy of the master cache,
      # but the master cache isn't updated until a merge to the master branch.
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-package-cache-${{ steps.this_branch.outputs.name }}
          restore-keys: |
            conan-package-cache-master

      - name: Setup Python environment
        uses: actions/setup-python@v2

      - name: Install/Upgrade Conan
        run: pip3 install --upgrade conan

      - name: Create build directory
        run: cmake -E make_directory ${{ github.workspace }}/build

      - name: Configure
        working-directory: ${{ github.workspace }}/build
        run: |
          conan profile update settings.compiler=${{ matrix.compiler }} default
          conan profile update settings.compiler.version=${{ matrix.compiler_version }} default
          conan profile update settings.compiler.libcxx=${{ matrix.compiler_libcxx }} default
          conan install .. -s build_type=${{ env.BUILD_TYPE }} -pr:b default --build missing

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: conan build ..

      - name: Package
        working-directory: ${{ github.workspace }}/build
        run: conan package ..

      - name: Retrieve artifact information
        working-directory: ${{ github.workspace }}/build
        id: artifact_data
        run: |
          echo "::set-output name=name::$(cat artifact_name.txt)"
          echo "::set-output name=path::$(cat artifact_path.txt)"

      - name: Upload artifact information, part 1
        uses: actions/upload-artifact@v3
        with:
          name: artifact_name_${{ matrix.name }}
          path: ./build/artifact_name.txt

      - name: Upload artifact information, part 2
        uses: actions/upload-artifact@v3
        with:
          name: artifact_path_${{ matrix.name }}
          path: ./build/artifact_path.txt

      - name: Upload artifact (${{ matrix.name }})
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact_data.outputs.name }}
          path: ${{ steps.artifact_data.outputs.path }}

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-release
    steps:
      - name: Create a new release
        uses: actions/create-release@v1
        id: release_data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ env.BUILD_TYPE }}
          draft: false
          prerelease: false

      - name: Save release information
        run: echo '${{ steps.release_data.outputs.upload_url }}' > upload_url.txt

      - name: Upload release information
        uses: actions/upload-artifact@v2
        with:
          name: upload_url
          path: upload_url.txt

  upload-release:
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: mac
            os: macos-latest
          - name: windows
            os: windows-latest

    steps:
    - name: Download artifact information, part 1
      uses: actions/download-artifact@v2
      with:
        name: artifact_name_${{ matrix.name }}

    - name: Download artifact information, part 2
      uses: actions/download-artifact@v2
      with:
        name: artifact_path_${{ matrix.name }}

    - name: Download release information (${{ matrix.name }})
      uses: actions/download-artifact@v2
      with:
        name: upload_url

    - name: Load release information (${{ matrix.name }})
      id: release_data
      run: |
        echo "::set-output name=upload_url::$(cat upload_url.txt)"

    - name: Load artifact information (${{ matrix.name }})
      id: artifact_data
      run: |
        echo "::set-output name=name::$(cat artifact_name_${{ matrix.name }})"
        echo "::set-output name=path::$(cat artifact_path_${{ matrix.name }})"

    - name: Upload release artifact (${{ matrix.name }})
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_data.outputs.upload_url }}
        asset_name: ${{ steps.artifact_data.outputs.name }}
        asset_path: ${{ steps.artifact_data.outputs.path }}
        asset_content_type: application/octet-stream
