name: sanitize-linux-clang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  BUILD_TYPE: Debug
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Acquire branch name
        id: current_branch
        run: echo "::set-output name=name::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Cache Conan
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: conan-cache-${{ steps.current_branch.outputs.name }}
          restore-keys: conan-cache-main
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install Conan
        run: pip3 install --upgrade conan
      - name: Update Conan profile
        run: conan profile detect -f
      - name: Pull Dependencies
        run: conan install . -of build -s build_type=${{ env.BUILD_TYPE }} -pr:b=default -b=missing
      - name: Configure
        run: cmake --preset dev-gcc
      - name: Build
        run: cmake --build --preset dev-gcc
